name: security-pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # DSOMM: Patch Management | Dependency vulnerability scanning (SCA)
  sca-trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.65.0
          trivy --version
      - name: Trivy fs scan (SCA)
        run: |
          trivy fs --severity HIGH,CRITICAL --ignore-unfixed --exit-code 0 --format table .
          echo "AUDIT-MODE: exit-code 0, na baseline naar 1"

  # DSOMM: Secure Build | Static Application Security Testing (SAST)
  sast-semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
        continue-on-error: true

  # DSOMM: Secrets Management | Secret scanning
  secret-gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
